# Generated by Django 4.2.15 on 2024-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
