# Generated by Django 4.2.15 on 2024-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewed_remove_book_content_remove_book_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewed',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
