# Generated by Django 4.2.15 on 2024-08-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_alter_book_author_alter_reviewed_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewed',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.book'),
        ),
    ]
