# Generated by Django 4.2.15 on 2024-08-29 12:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviewed_author_alter_reviewed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
