# Generated by Django 4.2.15 on 2024-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_book_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_here',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
